[package]
name = "lua_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
mlua = { version = "0.9.0-rc.1", features = ["luajit"] }
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
